version: '3.8' # It's a good practice to specify the version

services:
  node:
    build:
      context: ./node  # Update to the correct folder where your Dockerfile is located
      dockerfile: Dockerfile
    image: cookie8monster/super-app-node:latest # Use the correct image name
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: super-app

  php:
    build:
      context: ./php  # Update to the correct folder where your Dockerfile is located
      dockerfile: Dockerfile
    image: cookie8monster/super-app-php:latest # Use the correct image name
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: super-app

  db:
    image: mariadb:latest  # Use MariaDB as an alternative to MySQL
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
