version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: php-web
    ports:
      - "3000:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - app-network
    platform: linux/amd64  # Specify the platform

  php-fpm:
    image: php:8.0-fpm
    container_name: php-fpm
    volumes:
      - ./php:/var/www/html
    networks:
      - app-network
    platform: linux/amd64  # Specify the platform

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    platform: linux/amd64  # Specify the platform

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
