services:
  web:
    image: nginx:alpine
    container_name: php-web
    ports:
      - "3000:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./php
    container_name: php-fpm
    volumes:
      - ./php:/var/www/html
    networks:
      - app-network

  db:
    image: mysql/mysql-server:5.7  # Consider a different MySQL image that supports ARM
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
