version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: php-web
    ports:
      - "3000:80"
    platform: linux/amd64  # Add this line
    volumes:
      - ./php:/var/www/html

  php-fpm:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-fpm
    platform: linux/amd64  # Add this line
    volumes:
      - ./php:/var/www/html

  db:
    image: mysql:5.7
    container_name: mysql-db
    platform: linux/amd64  # Add this line
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
