version: '3.8'

services:
  web:
    image: nginx:stable-alpine
    container_name: php-web
    ports:
      - "3000:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    image: arm64v8/php:8.1-fpm
    container_name: php-fpm
    volumes:
      - ./php:/var/www/html
    networks:
      - app-network

  db:
    image: arm64v8/mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
